# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    filter_sets:

        my_thumb_filter_max:
            filters:
                thumbnail:
                    size: [ 300, 300 ]
                    mode: outbound
                    allow_upscale: true

        my_thumb_filter_min:
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: outbound
                    allow_upscale: true
